# Generated by Django 3.2.24 on 2024-06-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logins',
        ),
        migrations.RemoveField(
            model_name='main',
            name='clinicid',
        ),
    ]
